import { Suspense } from "react";
import UserManagementView from "@/view/user-management";
import Loading from "./loading";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserManagement() {
  return (
    <Suspense fallback={<Loading />}>
      <UserManagementView />
    </Suspense>
  );
}
