import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
    <div className="container mx-auto w-full justify-center items-center text-center">
      <header>
        <h1>Ini Blog</h1>
        <div className="flex flex-row gap-2">
          <Link href={"#profile"}>Profile</Link>
          <Link href={"#about-me"}>About-Me</Link>
          <Link href={"#skill"}>Skill</Link>
          <Link href={"#experience"}>Experience</Link>
        </div>
      </header>
      <main className="flex flex-col gap-2">
        <section id="profile" className="h-[500px] bg-orange-50">
          <h2>Section Profile</h2>
        </section>
        <section id="about-me" className="h-[500px] bg-red-50">
          <h2>Section About-me</h2>
        </section>
        <section id="skill" className="h-[500px] bg-blue-50">
          <h2>Section Skill</h2>
        </section>
        <section id="experience" className="h-[500px] bg-purple-50">
          <h2>Section Experience</h2>
        </section>
      </main>
    </div>
  );
}
